apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment2
  name: nginx-deployment2
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 #extra
      maxUnavailable: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment2
    spec:
      containers:
      - image: nginx:1.15.0
        name: nginx
        resources: {}
status: {}
